library(knitr)
library(markdown)
# setwd("~/GitHub/DataCleaningProject")
setwd("~/GitHub/DataCleaningProject")
knit("run_analysis.Rmd", encoding="ISO8859-1")
markdownToHTML("run_analysis.md", "run_analysis.html")